language: php

php:
  - 7.0
  - 7.1
  - nightly

install:
  - travis_retry composer install --no-interaction --dev --no-suggest

script:
  - vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)
